name: Node.js Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: Change to 'valsco' directory
        run: ls
        
      - name: List files in 'valsco' directory
        working-directory: ./valsco
        run: ls
        

      - name: Install dependencies in 'valsco' directory
        working-directory: ./valsco
        run: npm i
     

      - name: Run 'npm start' in 'valsco' directory
        working-directory: ./valsco
        run: docker build . --file Dockerfile --tag --image-file-name
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
  
